# -*- coding: utf-8 -*-
"""Email_Spam_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_twAIE2sMG7lg2Hc4uArF5j3C_ef_zlO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
from sklearn.svm import SVC

df = pd.read_csv('/content/email.csv')

df.head()

df.info()

sns.countplot(x='Category', data=df)

plt.pie(df['Category'].value_counts(), labels=df['Category'].unique(), autopct='%1.1f%%')
plt.show()

le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])

df['Category']

X = df.drop('Category', axis=1)
y = df['Category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

cv = CountVectorizer()
cv.fit(X_train['Message'])
x_train_v = cv.transform(X_train['Message'])
x_test_v = cv.transform(X_test['Message'])

lr = LogisticRegression()
lr.fit(x_train_v, y_train)

accu = lr.score(x_test_v, y_test)
print(accu)
precision = classification_report(y_test, lr.predict(x_test_v))
print(precision)
confusion_mat = confusion_matrix(y_test, lr.predict(x_test_v))
print(confusion_mat)

sns.heatmap(confusion_mat, annot=True, fmt='d')

dt = DecisionTreeClassifier( criterion='entropy', max_depth=5 , random_state=42 )
dt.fit(x_train_v, y_train)

plt.figure(figsize=(20,10))
plot_tree(dt, filled=True, feature_names=cv.get_feature_names_out(), class_names=['ham', 'spam', 'unknown'])
plt.show()

accu = dt.score(x_test_v, y_test)
print(accu)

precision = classification_report(y_test, dt.predict(x_test_v))
print(precision)

confusion_mat = confusion_matrix(y_test, dt.predict(x_test_v))
print(confusion_mat)

svm = SVC()
svm.fit(x_train_v, y_train)

accu = svm.score(x_test_v, y_test)
print(accu)

precision = classification_report(y_test, svm.predict(x_test_v))
print(precision)

confusion_mat = confusion_matrix(y_test, svm.predict(x_test_v))
print(confusion_mat)

while True:
    user_input = input("Enter an email to classify (or type 'exit' to quit): ")
    if user_input.lower() == 'exit':
        break

user_vector = cv.transform([user_input])
prediction = lr.predict(user_vector)[0]
if prediction == 1:
  print("🛑 This email is likely **SPAM**.\n")
else:
  print("✅ This email looks **NOT SPAM**.\n")

